version: '3'
services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    tty: true
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: root
      POSTGRES_DB: phone_books
    ports:
      - "5432:5432"
#     volumes:
#       - db:/var/lib/postgresql/data


# volumes:
#   db: